---
- name: Bienvenidos a lab con ansible
  hosts: local
  vars:
    ambiente: dev
  tasks:
    - name: Imprimir mensaje
      ansible.builtin.debug:
        msg: "Hola desde Ansible! Host {{ inventory_hostname }}"
    
    - name: Escribir mi nombre en el file
      ansible.builtin.copy:
        content: "Ansible funcionando mi nombre es Luis Gerardo Asuncion Chira y estoy en {{ ambiente }}"
        dest: ./saludo.txt

    - name: Escribir mi nombre en el file 2
      ansible.builtin.copy:
        content: "Este es el segundo archivo de evidencia de Luis Gerardo Asuncion Chira"
        dest: ./evidencia2.txt


# when: ambiente == dev #prod

# Subir capturas de lo que consideran relevante para evidenciar
# su trabajo. Subir en formato .pdf
